# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: postgresql
  encoding: utf8
  schema_search_path: public
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: <%= ENV.fetch('POSTGRES_HOST', '127.0.0.1') %>
  port: <%= ENV.fetch('POSTGRES_PORT', '5432') %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5)%>

development:
  <<: *default
  database: <%= ENV['POSTGRES_DB'] %>

test:
  <<: *default
  database: <%= "#{ENV['POSTGRES_DB']}_test" %>


production:
  <<: *default
  database: <%= ENV['POSTGRES_DB'] %>